[package]
name = "latr"
version = "0.1.0"
authors = ["arnaud.fernandes <arnaud.fernandes@laposte.net>"]

[lib]
name = "latr"
path = "src/lib.rs"

[dependencies]
clap = "1"
walkdir = "0.1"
nickel = "*"
lazy_static = "0.1.*"
git2 = "0.3"
tempdir = "0.3"

